version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:3fbc466c4ef29b41c7e6ebb5679bccea2c91141bc9cd473cff1f9d29269babd2
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:7fdd3e9ab2f9797c280deeb1a97d8158b28bd33eb98531b928cb006270712d2e
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"