version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:58a345bc2dbafed28c2deb5096dc8cb6c4a11958da9d890c02f5a3d870eef836
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:fe746a766d2614144c9d97d3b6f9d1efe87e56c80109c837d1510289189ab687
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"