version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:18eb8917574b2e741783a0f04fb59ae806608e3cab35d33b3c7e6e37bd5bdfd8
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:6957d50ac5322fce3c131cee1aeb089afbf17a806ef813bbd98179f0ec28ff65
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"