version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:ee0d1ad34ee94a33a5d3d04ca306b8de683c736433bd853bf12a780f2b9ce683
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.5-alpine@sha256:c44ef264fe352dff5100499545dcb423570df8777d24f2fd96233d801e6fb901
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"