version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:235385e0441ff758cc0b94f68a627b7b0fd4b76bc9f737bea1f8672f4c689e35
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:2065319505112ffe74ffb1636199075c5dadf1f786e78f4f25859e643eeea878
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"