version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:ee0d1ad34ee94a33a5d3d04ca306b8de683c736433bd853bf12a780f2b9ce683
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:2b4d28f53aa285e5566963c5592a365bfbdd7b38a8f53550ca1ef5fe00b10fd4
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"