version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:58a345bc2dbafed28c2deb5096dc8cb6c4a11958da9d890c02f5a3d870eef836
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:2564f9e429347326297055ba27092e8e575f9ee4fb409c960388a4b04ca9ebe4
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"