version: '2'
services:
  plugin:
    image: buildkite/plugin-tester:latest@sha256:235385e0441ff758cc0b94f68a627b7b0fd4b76bc9f737bea1f8672f4c689e35
    volumes:
      - ".:/plugin"
    depends_on:
      - ruby
  ruby:
    image: ruby:2.6-alpine@sha256:0f309d96a24fdd76b32d80de98d56f8457e61462d97a131708dab4f8e1edc664
    command: rake
    working_dir: /src
    volumes:
      - "./ruby:/src"