steps:
  - label: ":bash: Plugin"
    plugins:
      docker-compose#v2.5.1:
        run: plugin
  - label: ":ruby: Ruby"
    plugins:
      docker-compose#v2.5.1:
        run: ruby
  - label: "✨ Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: junit-annotate
  - label: ":bash: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files: hooks/*